sar_mode: "ControlNet"

model: "dbcr"

train:
  batch_size: 8
  num_workers: 2
  num_epochs: 15
  lr: 0.0001
  T: 1000
  sigmoid_k: 10.0
  load_filename: "dbcr_no_sar_naf_v2.pth"
  resume_filename: "None"

huggingface:
  repo_id: "LucioLuque/lama"
  save_filename: "dbcr_controlnet_v2.pth"
  version: 2
  notes: "Con ControlNet, lr=1e-4, grad clip, scheduler, LA VOLVI A HACER PORQUE TENIA ALGO MAL LA CONTROLNET"
