sar_mode: "ControlNet"   

model: "dbcr_complex"

train:
  batch_size: 4         
  num_workers: 2
  num_epochs: 15
  lr: 0.0001
  T: 1000
  sigmoid_k: 10.0
  load_filename: "None"  # entrenar desde cero
  # resume_filename: "dbcr_complex_v3.pth"
  resume_filename: "dbcr_complex_v4.pth"

model_args:
  image_channels: 6
  condition_channels: 6
  sar_channels: 2
  base_channels: 64
  time_dim: 128
  num_heads: 1
  window_size_sf0: 8        # window attention en sf0 (necesario en 256x256)
  window_size_not_sf0: None  # global attention en sf1/sf2/sf3/sf_mid
  use_checkpoint: true       # gradient checkpointing para ahorrar VRAM
  include_encoder_4: false     # incluir encoder_4 (con 512 canales) para mejorar resultados a costa de más VRAM


huggingface:
  repo_id: "LucioLuque/lama"
  save_filename: "dbcr_complex_v7.pth"
  version: 7
  notes: "DBCR con NAFBlocks + SFBlocks (cross-attention SAR), window sf0=8, checkpoint ON, sin encoder_4. CON 6 BANDAS + 15 epocas + 15 epocas + 15 epocas, es decir 60 epocas. Parte desde complex v4 que fueron 45."