#Config de un experimento, para cada uno de este modelo fuimos variando este archivo.
sar_mode: "ControlNet"

model: "dbcr"

train:
  batch_size: 8
  num_workers: 2
  num_epochs: 30
  lr: 0.0001
  T: 1000
  sigmoid_k: 10.0
  load_filename: "dbcr_no_sar_naf_v2.pth"
  resume_filename: "None"

huggingface:
  repo_id: "LucioLuque/lama"
  save_filename: "dbcr_controlnet_v3.pth"
  version: 3
  notes: "Con ControlNet, lr=1e-4, grad clip, scheduler, controlnet 30 epocas"
