sar: true
 
adapt:
  pretrained_path: ""   # no usado en modo SAR
 
train:
  batch_size: 4
  num_workers: 2
  epochs_frozen: 1
  epochs_full: 1
  lr_frozen: 1e-3
  lr_full: 1e-4
 
eval:
  batch_size: 4
  num_workers: 2
 
huggingface:
  repo_id: "LucioLuque/lama"
  base_filename: "lama_sar_pretrained_v1.pth"     # modelo base para train
  save_prefix: "lama_sar_finetuned"               # prefijo para guardar finetuned (train)
  no_sar_fine_prefix: "lama_no_sar_finetuned"     # prefijo fuente para adapt SAR
  adapt_save_prefix: "lama_sar_pretrained"        # prefijo para guardar el adaptado desde no-SAR