sar: false

adapt:
  pretrained_path: null          # null = big-lama por defecto
  save_name: lama_no_sar_pretrained.pth

train:
  model_path: saved_models/lama_no_sar_pretrained.pth
  save_path:  saved_models/lama_no_sar_finetuned.pth
  batch_size: 4
  num_workers: 2
  epochs_frozen: 10
  epochs_full:   100
  lr_frozen: 1e-3
  lr_full:   1e-4

eval:
  model_path: saved_models/lama_no_sar_finetuned.pth
  batch_size: 4
  num_workers: 2